README.md, package.json, src/__snapshots__/schema.types.spec.ts.snap, yarn.lock
I have reached GraphQL folks on Discord, and they should be fixing urgent things on graphql projects. So hopefully they will soon get to `express-graphql` as well. Meanwhile I downgraded `graphql` package to supported version by `express-graphql` as we are not using anything from newer versions.
Before:
After:
=> Downgrade to graphql 15.8.0 to match express-graphql peer

src/graphql.spec.ts
Salvaged from #11, just calling of `createGraphQLMiddleware` and some error states.
Closes #11
=> chore(spec): Add spec for createGraphQLMiddleware

.github/workflows/release.yml, package.json
The motivation here is to be able to use the package stright from GitHub. (Not sure how yarn handles it but [npm's prepack](https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts) is explicitly ran when installing git dependencies).
I have also removed the `build` step in the release flow to avoid running `tsc` twice.
=> chore(package): Add prepack script

CHANGELOG.md, package.json, yarn.lock
- Updated and pin OneSDK to 1.5.1
- Removed explicit dependency on AST and Parser
@Jakub-Vacek as you suggested this locking in [PR18](https://github.com/superfaceai/one-service/pull/18#discussion_r884788024). I gave it some thoughts and I believe you were right and it is good idea.
=> Update and pin OneSDK

CHANGELOG.md, src/errors.spec.ts, src/errors.ts, src/index.ts, src/one_sdk.ts
Fixes #24.
The root cause of this issue is that OneSDK sometimes throws errors which don't inherit JS's `Error` object, causing the `Unexpected error value` seen in #24.
Here I have added a custom error wrapper which remaps OneSDK errors to extended Error object. graphql-js automatically picks `extensions` property and propagates it further, resulting more detailed output:
Additionally users can provide their custom `customFormatErrorFn` to expose information they need.
=> feat: Map OneSDK errors to be GraphQL-compatible

package.json, yarn.lock
This PR updates @superfaceai dependencies to latests versions
- OneSDK 2.3.0
- Parser 2.1.0
- AST 1.3.0
It should resolve the issue when OneService doesn't start with `Error: Specified AST is not compatible with linter` error.
It also adds AST as explicit dependency instead of using it transitively from Parser/OneSDK.
=> Update OneSDK, Parser and AST

.github/workflows/release.yml, CHANGELOG.md, src/one_sdk.spec.ts, src/one_sdk.ts
This will fallback to `{}` empty object if input isn't specified.
=> Input may be skipped in GQL, but needed for perform

CHANGELOG.md, package.json, yarn.lock
Explicitly bump OneSDK dependency to v2. 3.1. Although the patch version is covered by semver range, v2.3.0 contains a bug which is triggered by the GraphQL resolver, therefore the previous version shouldn't be used with OneService at all.
Refs: https://github.com/superfaceai/one-sdk-js/pull/333
=> chore: Update OneSDK to v2.3.1

.gitignore, CHANGELOG.md, package.json, src/graphql.ts, src/one_sdk.spec.ts, src/one_sdk.ts, yarn.lock
Example use with dynamic schema and OneSDK configuration:
```ts
import { SuperJsonDocument } from '@superfaceai/ast';
import {
normalizeSuperJsonDocument,
SuperfaceClient,
} from '@superfaceai/one-sdk';
import express, { Handler } from 'express';
import { createGraphQLMiddleware } from '../graphql';
import { generate as generateSchema } from '../schema';
import superOne from './super_one.json';
import superTwo from './super_two.json';
const superjsons: Record<string, SuperJsonDocument> = {
one: superOne as unknown as SuperJsonDocument,
two: superTwo as unknown as SuperJsonDocument,
};
const handlers: Record<string, Handler> = {};
async function getHandler(id: string): Promise<Handler> {
if (!handlers[id]) {
const superJson = normalizeSuperJsonDocument(superjsons[id]);
const schema = await …
```
=> Allow to pass `getOneSdkInstance` in context

CHANGELOG.md, src/graphiql.ts
GraphiQL recently released v2.4.0, however page links to the latest version from unpkg with an integrity check.
Integrity check with newer version of GraphiQL fails and the page won't load at all.
This sets the version of GraphiQL to v2.4.0 with appropriate integrity check.
=> fix(graphiql): Specify ext. dependencies version

CHANGELOG.md, src/schema.ts
This PR fixes generating of _superJson introspection schema and resolver. Instead of loading it from file system it uses `SuperJsonDocument` passed from argument.
=> Generate _superJson introspection schema and resolver using SuperJson document from argument

CHANGELOG.md, src/__snapshots__/schema.types.spec.ts.snap, src/fixtures/profile_with_empty_input_structure.supr, src/schema.types.spec.ts, src/schema.types.ts
This PR fixes generating schema for Comlink profiles with empty use case input fields.
Generated GraphQL schema must define one or more input fields.
=> Fix generating schema for empty input fields

src/__snapshots__/schema.types.spec.ts.snap, src/schema.types.spec.ts, src/schema.types.ts
Fixed #44 
Lets have following profile
```
name = "scope/name"
version = "1.0.0"
usecase UseCase safe {
input {
field string
}
}
```
Possible solution is to defined own `None` type representing null.
```gql
query MyQuery {
ScopeName {
UseCase(input: {field: "f"}) {
result
}
}
}
```
=> Handle usecase without result as result being nullable boolean

CHANGELOG.md, src/provider.spec.ts, src/provider.ts
This PR adds loading provider json from registry.
Unlike `resolveProfileAst`, `resolveProviderJson` isn't loading provide.json from registry, because it is relying on bind call response in OneSDK. I didn't notice that when implementing.
=> Add loading from registry

.gitignore, CHANGELOG.md, src/__snapshots__/schema.spec.ts.snap, src/__snapshots__/schema.types.spec.ts.snap, src/fixtures/profile_multiple_use_cases.supr, src/one_sdk.spec.ts, src/one_sdk.ts, src/schema.spec.ts, src/schema.types.spec.ts, src/schema.types.ts, src/schema.utils.spec.ts, src/schema.utils.ts
This PR fixes three issues:
1. Provider option type wasn't unique. It got defined for every use-case with the same name. The solution was to move it up to profile level and pass to a function creating use-case schema – fixed in this [commit](https://github.com/superfaceai/one-service/commit/a4606f4f26193456b851292502ee5f8d4a618160)
2. Comlink provider name is valid if contains only the following characters`[a-z][a-z0-9_-]` on the other side GQL allows `[_a-zA-Z][_a-zA-Z0-9]` so there is a problem with `-` char. So we need to sanitize it, but in a way it is reversible for mapping to the provider name specified in `super.json`. @jnv proposed replacing `-` with a capitalized letter, unfortunately in corner case `-` can be the last char in the name e.g. `provider-` (I know this should be …
=> Fix non unique type for provider option and invalid field names

CHANGELOG.md, src/__snapshots__/schema.spec.ts.snap, src/__snapshots__/schema.types.spec.ts.snap, src/schema.spec.ts, src/schema.ts, src/schema.types.spec.ts, src/schema.types.ts, src/spec_helpers.ts
For more than one profile using the same provider, provider input type was created multiple times, which caused error `Schema must contain uniquely named types but contains multiple types named`
This PR is fixing it by creating all provider configuration before creating profile types.
Follow up for https://github.com/superfaceai/one-service/pull/46
=> Provider config GQL type name collision fix

CHANGELOG.md, src/one_sdk.spec.ts, src/one_sdk.ts
OneService was passing empty object `{}`, if something is passed, OneSDK uses it and ignores values in `super.json`
https://github.com/superfaceai/one-sdk-js/blob/69d86d18b8b6d2a1b1537da23cbd708c5409e0b9/src/core/profile-provider/profile-provider.ts#L129
=> Security and parameters loading from super.json

CHANGELOG.md, src/__snapshots__/schema.spec.ts.snap, src/fixtures/test.provider.json, src/one_sdk.spec.ts, src/one_sdk.ts, src/schema.types.ts, src/schema.utils.spec.ts, src/schema.utils.ts
Also, security ids, can contain `-`, so we need to sanitize and desanitize them. Similarly, as for provider name in https://github.com/superfaceai/one-service/pull/46
=> Sanitize security ids for GQL schema

CHANGELOG.md, src/__snapshots__/schema.spec.ts.snap, src/__snapshots__/schema.types.spec.ts.snap, src/schema.types.ts
This PR fixes mapping Comlink `number` primitive type to GraphQL `Float`. Comlink number can be either integer or float.
=> Fix mapping Comlink `number` primitive type to GraphQL `Float`

CHANGELOG.md, src/__snapshots__/schema.spec.ts.snap, src/__snapshots__/schema.types.spec.ts.snap, src/fixtures/profile_with_empty_nested_object_in_input.supr, src/fixtures/profile_with_empty_nested_object_in_result.supr, src/fixtures/profile_with_empty_result.supr, src/schema.spec.ts, src/schema.types.spec.ts, src/schema.types.ts
This PR fixes mapping empty objects to GraphQL. GraphQL is more strict than Comlink and do not allow empty objects in GraphQL schema.
Empty objects can be part of Comlink input and result.
=> Fix mapping empty objects to GraphQL
